# Generated by Django 2.2.5 on 2020-01-25 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ans',
            name='ans',
            field=models.TextField(),
        ),
    ]
