# Generated by Django 2.2.5 on 2020-01-25 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_auto_20200125_0704'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ans',
        ),
    ]
